# Dockerfile.listen_socket
FROM python:3.12-slim-bullseye

# Set the working directory
WORKDIR /code

RUN apt-get update && apt-get install -y netcat-openbsd

# Copy the requirements file and install dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copy the project files
COPY ./src /code/

# Set the command to run the socket listener
CMD ["python", "manage.py", "fake_log"]