FROM ubuntu:latest
RUN apt-get update && apt-get install -y rsyslog

# Create log directories
RUN mkdir -p /var/log/nginx

COPY rsyslog.conf /etc/rsyslog.conf

# Set permissions
RUN chmod 644 /etc/rsyslog.conf && \
    chmod -R 755 /var/log

CMD ["rsyslogd", "-n"]