[build]
builder = "nixpacks"
buildCommand = "docker-compose build"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
    "Dockerfile.*",
    "docker-compose.yml",
    "logger-frontent/**"
]

[deploy]
startCommand = "docker-compose up"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "app"
healthcheck = "/health"
port = 8000

[[services]]
name = "nextjs"
port = 3000