# Generated by Django 4.2.16 on 2024-11-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255, unique=True)),
                ('added_now', models.DateTimeField(auto_now_add=True)),
                ('update_now', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(max_length=10, unique=True)),
                ('added_now', models.DateTimeField(auto_now_add=True)),
                ('update_now', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method_type', models.CharField(max_length=10, unique=True)),
                ('added_now', models.DateTimeField(auto_now_add=True)),
                ('update_now', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=30)),
                ('log_string', models.TextField()),
                ('added_now', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries_demo', to='home.host')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries_demo', to='home.level')),
                ('request_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries_demo', to='home.requestmethod')),
            ],
        ),
    ]
