# Generated by Django 4.2.16 on 2024-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='date_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
